# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.unauthenticated_error import UnauthenticatedError


class UnauthorizedError(ApiError):
    def __init__(self, body: UnauthenticatedError):
        super().__init__(status_code=401, body=body)
