# This file was auto-generated by Fern from our API Definition.

from .types import (
    TestrecordCreateParamsCustomInputsValue,
    TestrecordCreateParamsCustomLabelsValue,
    TestrecordCreateParamsCustomOutputsValue,
)

__all__ = [
    "TestrecordCreateParamsCustomInputsValue",
    "TestrecordCreateParamsCustomLabelsValue",
    "TestrecordCreateParamsCustomOutputsValue",
]
