# This file was auto-generated by Fern from our API Definition.

from .testrecord_create_params_custom_inputs_value import TestrecordCreateParamsCustomInputsValue
from .testrecord_create_params_custom_labels_value import TestrecordCreateParamsCustomLabelsValue
from .testrecord_create_params_custom_outputs_value import TestrecordCreateParamsCustomOutputsValue
from .testrecord_create_params_model_debug_info_value import TestrecordCreateParamsModelDebugInfoValue
from .testrecord_create_params_model_params_value import TestrecordCreateParamsModelParamsValue

__all__ = [
    "TestrecordCreateParamsCustomInputsValue",
    "TestrecordCreateParamsCustomLabelsValue",
    "TestrecordCreateParamsCustomOutputsValue",
    "TestrecordCreateParamsModelDebugInfoValue",
    "TestrecordCreateParamsModelParamsValue",
]
