# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.file_url import FileUrl
from ...types.json_object import JsonObject

TestrecordCreateParamsCustomOutputsValue = typing.Union[str, FileUrl, JsonObject]
