# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.file_url import FileUrl
from ...types.json_object import JsonObject

TestcaseUpdateParamsCustomInputsValue = typing.Union[FileUrl, JsonObject, str, int, float, bool]
