# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .role_enum import RoleEnum
from .data_type_enum import DataTypeEnum
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CustomVariable(UncheckedBaseModel):
    """
    Custom variable model with name, description, role and data type.
    """

    name: str
    description: typing.Optional[str] = None
    role: RoleEnum
    data_type: DataTypeEnum

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
