# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class DataTypeEnum(str, enum.Enum):
    """
    Enum for data types.
    """

    TEXT = "text"
    FILE_URL = "file_url"
    JSON_OBJECT = "json_object"

    def visit(
        self,
        text: typing.Callable[[], T_Result],
        file_url: typing.Callable[[], T_Result],
        json_object: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is DataTypeEnum.TEXT:
            return text()
        if self is DataTypeEnum.FILE_URL:
            return file_url()
        if self is DataTypeEnum.JSON_OBJECT:
            return json_object()
