# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
import typing
import typing

if typing.TYPE_CHECKING:
    from .json_object import JsonObject
JsonObjectOutputValue = typing.Union[typing.Dict[str, "JsonObject"], typing.List["JsonObject"], str, int, float, bool]
