# This file was auto-generated by Fern from our API Definition.

import typing

from .json_object import JsonObject

JsonObjectOutputValue = typing.Union[typing.Dict[str, JsonObject], typing.List[JsonObject], str, int, float, bool]
