# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
from .test_case import TestCase
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class PaginatedTestcaseResponse(UncheckedBaseModel):
    count: int
    next: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL to fetch the next page of testcases.
    """

    previous: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL to fetch the previous page of testcases.
    """

    results: typing.List[TestCase] = pydantic.Field()
    """
    The list of Testcases retrieved in this page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
