# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
from .prompt_model_params_value import PromptModelParamsValue
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Prompt(UncheckedBaseModel):
    org_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The organization this resource belongs to.
    """

    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user this record belongs to.
    """

    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    is_archived: typing.Optional[bool] = None
    prompt_template: typing.Optional[str] = None
    model_params: typing.Optional[typing.Dict[str, typing.Optional[PromptModelParamsValue]]] = None
    root_id: typing.Optional[str] = None
    parent_id: typing.Optional[str] = None
    merge_parent_id: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    project_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    The ID of the project the prompt belongs to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
