# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class RoleEnum(str, enum.Enum):
    """
    Enum for role types.
    """

    INPUT = "input"
    OUTPUT = "output"
    LABEL = "label"
    METADATA = "metadata"

    def visit(
        self,
        input: typing.Callable[[], T_Result],
        output: typing.Callable[[], T_Result],
        label: typing.Callable[[], T_Result],
        metadata: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is RoleEnum.INPUT:
            return input()
        if self is RoleEnum.OUTPUT:
            return output()
        if self is RoleEnum.LABEL:
            return label()
        if self is RoleEnum.METADATA:
            return metadata()
