# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import pydantic_v1
from ..core.unchecked_base_model import UncheckedBaseModel


class Run(UncheckedBaseModel):
    id: typing.Optional[int] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None
    execution_start_time: typing.Optional[dt.datetime] = None
    execution_end_time: typing.Optional[dt.datetime] = None
    testset_id: typing.Optional[int] = None
    status: typing.Optional[str] = None
    limit_testcases: typing.Optional[int] = None
    source: typing.Optional[str] = None
    model_params: typing.Optional[typing.Dict[str, typing.Any]] = None
    notes: typing.Optional[str] = None
    scoring_config_id: typing.Optional[int] = None
    prompt_template: typing.Optional[str] = None
    scoring_start_time: typing.Optional[dt.datetime] = None
    scoring_end_time: typing.Optional[dt.datetime] = None

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
