# This file was auto-generated by Fern from our API Definition.

import typing
from .file_url import FileUrl
from .json_object import JsonObject

TestrecordCustomInputsValue = typing.Union[str, FileUrl, JsonObject]
