# This file was auto-generated by Fern from our API Definition.

import typing
from .file_url import FileUrl
from .json_object import JsonObject

TestCaseCustomLabelsValue = typing.Union[FileUrl, JsonObject, str, int, float, bool]
